//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string EMail { get; set; }
        public string Password { get; set; }
        public int GenderId { get; set; }
        public int RoleId { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int CountryId { get; set; }
        public string PhoneNumber { get; set; }
        public byte[] PhotoBytecode { get; set; }
        public Nullable<int> SpecialityId { get; set; }
        public Nullable<int> EventId { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual Events Events { get; set; }
        public virtual Genders Genders { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual Specialities Specialities { get; set; }
    }
}
